apiVersion: v1
kind: Namespace
metadata:
  name: paypal-contract-lower
  labels:
    app.kubernetes.io/part-of: paypal-contract-demo
    paypal.com/environment: lower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-spring
  namespace: paypal-contract-lower
  labels:
    app.kubernetes.io/name: orders-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders-spring
        paypal.com/environment: lower
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: orders-spring
          image: ghcr.io/danielshively-source/paypal-pact-harness-cd/orders-spring-wrapper:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: orders-spring
  namespace: paypal-contract-lower
spec:
  selector:
    app.kubernetes.io/name: orders-spring
  ports:
    - name: http
      port: 8080
      targetPort: http
